name: "PR CI :: Vercel"

on:
    issue_comment:
        types:
          - created

jobs:
    vercel_to_notion:
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request }}

        steps:
            - name: Get Vercel link
              run: |
                vercel_slug=$(grep -Po "\[Visit Preview\]\((https:.*?)\)" <<< "${{ github.event.comment.body }}") || [[ $? == 1 ]]
                vercel_link=$(grep -Po "(https:.*?).app" <<< "$vercel_slug") || [[ $? == 1 ]]
                echo "vercel_link=$vercel_link" >> $GITHUB_ENV

            - name: Update notion ticket
              if: ${{ env.vercel_link }}
              run: |
                notion_id=$(curl --location --request POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DB_ID }}/query" \
                --header 'Notion-Version: 2022-06-28' \
                --header 'Authorization: Bearer ${{ secrets.NOTION_API_KEY }}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                "filter": {
                  "and": [
                  {
                      "property": "test-formula",
                      "formula": {
                          "string": {"starts_with": "${{ github.head_ref }}"}
                      }
                  }
                ]
                },
                "sorts": [
                  {
                    "property": "Due",
                    "direction": "ascending"
                  }
                ]
                }'  | jq -rc '.results[0].id')
                curl --location --request PATCH "https://api.notion.com/v1/pages/$notion_id" \
                --header 'Notion-Version: 2022-06-28' \
                --header 'Authorization: Bearer ${{ secrets.NOTION_API_KEY }}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                  "properties": {
                    "Vercel": { "rich_text": [{
                        "text": {
                            "content": "${{ env.vercel_link }}",
                            "link": {"url": "${{ env.vercel_link }}"}
                        }
                    }] }
                  }
                }'
