name: "PR CI :: Link"

on:
    pull_request:
        types: [opened, reopened]

jobs:
    link_to_notion:
        runs-on: ubuntu-latest

        steps:
            - name: Update notion ticket
              run: |
                notion_id=$(curl --location --request POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DB_ID }}/query" \
                --header 'Notion-Version: 2022-06-28' \
                --header 'Authorization: Bearer ${{ secrets.NOTION_API_KEY }}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                "filter": {
                  "and": [
                  {
                      "property": "Github Branch",
                      "formula": {
                          "string": {"starts_with": "${{ github.head_ref }}"}
                      }
                  }
                ]
                },
                "sorts": [
                  {
                    "property": "Target Date",
                    "direction": "ascending"
                  }
                ]
                }'  | jq -rc '.results[0].id')
                curl --location --request PATCH "https://api.notion.com/v1/pages/$notion_id" \
                --header 'Notion-Version: 2022-06-28' \
                --header 'Authorization: Bearer ${{ secrets.NOTION_API_KEY }}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                  "properties": {
                    "PR": {"url": "${{ github.event.repository.html_url }}/pull/${{ github.event.number }}"}
                  }
                }'
